<a href="https://colab.research.google.com/github/rajmishra-dev/ML-Learning-project/blob/main/ab-test/ml_ad_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing a Libray.!

In [20]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline
random.seed(55)

In [21]:
df = pd.read_csv('/content/ab_data.csv')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294478 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       294478 non-null  int64
 1   timestamp     294478 non-null  object
 2   group         294478 non-null  object
 3   landing_page  294478 non-null  object
 4   converted     294478 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.2+ MB

In [23]:
df.head()

   user_id                   timestamp      group landing_page  converted
0   851104  2017-01-21 22:11:48.556739    control     old_page          0
1   804228  2017-01-12 08:01:45.159739    control     old_page          0
2   661590  2017-01-11 16:55:06.154213  treatment     new_page          0
3   853541  2017-01-08 18:28:03.143765  treatment     new_page          0
4   864975  2017-01-21 01:52:26.210827    control     old_page          1

In [24]:
df.groupby(['group','converted']).agg('count')

                     user_id  timestamp  landing_page
group     converted
control   0           129479     129479        129479
          1            17723      17723         17723
treatment 0           129762     129762        129762
          1            17514      17514         17514

In [25]:
df.drop(df.query("group == 'control' and landing_page == 'new_page'").index, inplace=True)
df.drop(df.query("group == 'treatment' and landing_page == 'old_page'").index, inplace=True)

df.groupby(['group','converted']).agg('count')

                     user_id  timestamp  landing_page
group     converted
control   0           127785     127785        127785
          1            17489      17489         17489
treatment 0           128047     128047        128047
          1            17264      17264         17264

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290585 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       290585 non-null  int64
 1   timestamp     290585 non-null  object
 2   group         290585 non-null  object
 3   landing_page  290585 non-null  object
 4   converted     290585 non-null  int64
dtypes: int64(2), object(3)
memory usage: 13.3+ MB

###Cleaning Duplicated Users

In [27]:
df[df.duplicated(['user_id'], keep=False)]

      user_id                   timestamp      group landing_page  converted
1899   773192  2017-01-09 05:37:58.781806  treatment     new_page          0
2893   773192  2017-01-14 02:55:59.590927  treatment     new_page          0

In [28]:
df.drop_duplicates(['user_id'], inplace=True)

In [29]:
assert len(df['user_id'].unique()) == df['user_id'].size

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290584 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       290584 non-null  int64
 1   timestamp     290584 non-null  object
 2   group         290584 non-null  object
 3   landing_page  290584 non-null  object
 4   converted     290584 non-null  int64
dtypes: int64(2), object(3)
memory usage: 13.3+ MB

In [31]:
df['converted'].mean()

np.float64(0.11959708724499628)

In [32]:
df.groupby(['group']).describe()

            user_id                                                    \
              count           mean           std       min        25%
group
control    145274.0  788164.072594  91287.914601  630002.0  709279.50
treatment  145310.0  787845.719290  91161.564429  630000.0  708745.75

                                         converted                           \
                50%        75%       max     count      mean       std  min
group
control    788128.5  867208.25  945998.0  145274.0  0.120386  0.325414  0.0
treatment  787876.0  866718.75  945999.0  145310.0  0.118808  0.323564  0.0


           25%  50%  75%  max
group
control    0.0  0.0  0.0  1.0
treatment  0.0  0.0  0.0  1.0

In [33]:
df.groupby(['group']).agg({'converted' : ['sum', 'count', 'mean']})

          converted
                sum   count      mean
group
control       17489  145274  0.120386
treatment     17264  145310  0.118808

In [34]:
df.groupby(['group']).agg({'converted' : ['sum', 'count', 'mean']})

          converted
                sum   count      mean
group
control       17489  145274  0.120386
treatment     17264  145310  0.118808

In [35]:
df[['group','converted']].groupby(['group']).agg('mean').T

group       control  treatment
converted  0.120386   0.118808

Calculate Prob. of New and Old Pages
Respectively

In [36]:
p_old_page = df[['group', 'converted']].query("group == 'control'")['converted'].mean()
p_new_page = df[['group', 'converted']].query("group == 'treatment'")['converted'].mean()
act_p_diff = p_new_page - p_old_page

print('p_old_page:\t{}\np_new_page:\t{}\np_diff:\t\t{}'.format(p_old_page, p_new_page, act_p_diff))

p_old_page:	0.1203863045004612
p_new_page:	0.11880806551510564
p_diff:		-0.0015782389853555567

###Calculate Count of New and Old Pages Respectively

In [37]:
n_old = len(df[['group']].query("group == 'control'"))
n_new = len(df[['group']].query("group == 'treatment'"))

In [38]:
!git config --global user.email "shradkumar002@gmail.com"

In [39]:
!git config --global user.email

shradkumar002@gmail.com